plugins {
    id 'com.gradleup.shadow'
}

dependencies {
    api project(':everest-api')
    compileOnly('org.spigotmc:spigot-api:1.8.8-R0.1-SNAPSHOT') {
        exclude group: 'net.md-5', module: 'bungeecord-chat'
    }
    compileOnly 'net.md-5:bungeecord-chat:1.16-R0.4'
    implementation 'com.zaxxer:HikariCP:5.1.0'
    implementation 'com.mysql:mysql-connector-j:8.0.33'
    implementation 'org.slf4j:slf4j-nop:2.0.16'
}

processResources {
    filteringCharset = 'UTF-8'
    filesMatching('plugin.yml') {
        expand version: project.version
    }
}

shadowJar {
    archiveBaseName.set('EverestCore')
    archiveClassifier.set('')
    relocate 'com.zaxxer.hikari', 'com.everest.x.libs.hikari'
    relocate 'com.mysql', 'com.everest.x.libs.mysql'
    relocate 'org.slf4j', 'com.everest.x.libs.slf4j'
}

tasks.build.dependsOn tasks.shadowJar

tasks.jar {
    enabled = false
}
